replaced manual mapping with npm lib
airyhq/airy pull request #1098
Opened 2021-02-26 10:40 UTC by AudreyKj

2021-02-26 13:11 UTC, AudreyKj commented on lib/typescript/httpclient/index.ts
> +const camelcaseKeys = require('camelcase-keys');
here we have to use _require_ and not _import__ because the library supports TS but is not in TS

2021-02-26 13:12 UTC, AudreyKj commented on lib/typescript/httpclient/index.ts
> +
I added _mapMessage_  as a private method because it is used x3 in the library

2021-02-26 13:47 UTC, chrismatix approved these changes
Awesome! 💥

2021-02-26 13:56 UTC, chrismatix requested changes
So this is good already, but there are a few places where we should not map the keys and use the libraries [stop path](https://www.npmjs.com/package/camelcase-keys#stoppaths) feature:
- On every payload that has a `metadata.userData` path because that is user-supplied
- Every `message.content` field, because that schema is source specific

2021-03-01 09:50 UTC, AudreyKj commented on frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
> +          {`Filtered: ${filteredPaginationData.filteredTotal} Total: ${filteredPaginationData.total}`}
fixed this snake case in the UI, I am not so sure why this was not in camelCase...

2021-03-01 10:11 UTC, AudreyKj commented on lib/typescript/httpclient/payload/PaginatedResponse.ts
> +  paginationData: {previousCursor: string; nextCursor: string; total: number; filteredTotal: number};
updated PaginatedResponse type with _filteredTotal_ field

2021-03-01 10:37 UTC, AudreyKj commented on frontend/ui/src/reducers/data/conversations/index.ts
>  };
fixed snake_case in reducer for conversation data

2021-03-01 10:41 UTC, chrismatix approved these changes
Great work 👍

2021-03-01 10:56 UTC, merged