Feature/1022 change ingress hostnames
airyhq/airy pull request #1122
Opened 2021-03-03 10:00 UTC by ljupcovangelski

2021-03-03 10:10 UTC, chrismatix commented on infrastructure/helm-chart/templates/ingress.yaml
> +          - path: /ui/chatplugin
I am assuming that there would be a conflict with the `ui` pod here, so I would give this a different prefix

2021-03-03 10:10 UTC, chrismatix commented on frontend/ui/BUILD
> -    package_dir = "/usr/share/nginx/html/",
It's a bit weird that the ui package has to be aware of this change. I would prefer that we rewrite the path by stripping the prefix [in traefik](https://doc.traefik.io/traefik/middlewares/stripprefix/)

2021-03-10 07:59 UTC, lucapette requested changes
Looking good!

Minor suggestions for the docs. I requested changes so we make sure we remove the console.log statement

2021-03-10 07:59 UTC, lucapette commented on docs/docs/getting-started/installation/vagrant.md
> +http://airy.core/chatplugin//example. Refer to [the Airy Live Chat
```suggestion
http://airy.core/chatplugin/example. Refer to [the Airy Live Chat
```

2021-03-10 07:59 UTC, lucapette commented on docs/docs/sources/chat-plugin.md
> +`airy.core/chatplugin/` is not publicly accessible. The setup will only work for local web pages.
```suggestion
`airy.core/chatplugin` is not publicly accessible. The setup will only work for local web pages.
```

2021-03-10 07:59 UTC, lucapette commented on docs/docs/sources/chat-plugin.md
> +`http://airy.core/chatplugin//example?channel_id=CHANNEL_ID` and open it in your
```suggestion
`http://airy.core/chatplugin/example?channel_id=CHANNEL_ID` and open it in your
```

2021-03-10 07:59 UTC, lucapette commented on frontend/chat-plugin/BUILD
> +        "publicPath": "/chatplugin/",
trailing `/` probably not needed? I'm not sure

2021-03-10 07:59 UTC, lucapette commented on frontend/ui/src/index.tsx
> +console.log("public path", process.env.PUBLIC_PATH);
💣

2021-03-10 07:59 UTC, lucapette commented on infrastructure/scripts/provision/prerequisites.sh
> +curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -s -
:)

2021-03-10 08:27 UTC, lucapette commented on integration/ui/cypress.json
> +    "baseUrl": "http://airy.core",
```suggestion
    "baseUrl": "http://airy.core/ui",
```

2021-03-10 10:10 UTC, merged