Readme - now with nice graph-ical improvements
airyhq/airy pull request #1377
Opened 2021-03-25 10:54 UTC by sgarroum

Added Explainer Graphs
Graphical improvements

2021-03-25 13:12 UTC, chrismatix commented on README.md
> +![Airy_Explainer_Highlevel_Readme](https://user-images.githubusercontent.com/12533283/112460549-51e05d00-8d5f-11eb-802b-385c425dfaaf.png)
This a 1.3Mb png. Could you make it a jpeg and compress a little?

2021-04-06 07:03 UTC, lucapette requested changes
Applying the suggestions will fix the formatting problem.

I do agree with @chrismatix we should compress the image a little

2021-04-06 07:03 UTC, lucapette commented on README.md
> +- **🔌[WebSockets](https://airy.co/docs/core/api/websocket) to power real-time applications
```suggestion
- 🔌[WebSockets](https://airy.co/docs/core/api/websocket) to power real-time applications
```

2021-04-06 07:03 UTC, lucapette commented on README.md
> +- **🎣[Webhook](https://airy.co/docs/core/api/webhook) to listen to events and participate programmatically in conversations
```suggestion
- 🎣[Webhook](https://airy.co/docs/core/api/webhook) to listen to events and participate programmatically in conversations
```

2021-04-06 07:03 UTC, lucapette commented on README.md
> +- **💎[UI: From an inbox to dashboards](https://airy.co/docs/core/apps/ui/introduction)
```suggestion
- 💎[UI: From an inbox to dashboards](https://airy.co/docs/core/apps/ui/introduction)
```

2021-04-06 07:03 UTC, lucapette commented on README.md
> +- **⚡[APIs](https://airy.co/docs/core/api/introduction) to access your data
```suggestion
- ⚡[APIs](https://airy.co/docs/core/api/introduction) to access your data
```

2021-04-06 07:03 UTC, lucapette commented on README.md
> +- **💬 Connectors for all [conversational sources](https://airy.co/docs/core/sources/introduction)
```suggestion
- 💬 Connectors for all [conversational sources](https://airy.co/docs/core/sources/introduction)
```

2021-04-06 13:45 UTC, lucapette commented on README.md
> +![Airy_Explainer_Highlevel_Readme](https://user-images.githubusercontent.com/12533283/112460549-51e05d00-8d5f-11eb-802b-385c425dfaaf.png)
```suggestion
![Airy_Explainer_Highlevel_Readme](https://user-images.githubusercontent.com/124274/113720584-18a8d500-96ef-11eb-97c3-362eebd6253d.jpeg)
```

2021-04-06 13:59 UTC, lucapette approved these changes

2021-04-06 13:59 UTC, merged