Point custom instance from UI local
airyhq/airy pull request #2879
Opened 2022-02-22 11:11 UTC by AitorAlgorta

closes #2774 

Right now the websocket doesn't work if you point to an instance

2022-02-22 15:30 UTC, AudreyKj approved these changes

2022-02-23 11:18 UTC, chrismatix requested changes
Not ready yet

2022-03-11 11:26 UTC, chrismatix reviewed
lgtm

2022-03-11 11:26 UTC, chrismatix approved these changes

2022-03-11 14:03 UTC, merged