Feature/3693 api components installer
airyhq/airy pull request #3761
Opened 2022-09-22 13:37 UTC by juan-sebastian

closes #3693

2022-09-22 13:52 UTC, chrismatix commented on backend/components/installer/src/main/java/co/airy/core/components/installer/CatalogHandler.java
> +        git.pull();
curious: What's the reason for using this over the GitHub tree API you mentioned?

2022-10-17 09:59 UTC, ljupcovangelski submitted a review, later dismissed
The Helm chart code looks good :+1: 

I don't fully understand why are we using a `cache`. Is it only for listing the installed components? I think the existing approach by fetching the a list of ConfigMaps worked well. It reduces the complexity (no cache) and the component is anyway useless without the ConfigMap.

2022-10-17 11:49 UTC, ljupcovangelski commented on backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandlerCacheManager.java
> +            helmJobHandler.waitForCompletedStatus(api, job);
As install/uninstall can take some time, it is good that we wait for the job to be completed successfully before resetting the cache :+1:

2022-10-17 11:59 UTC, chrismatix requested changes

2022-10-17 11:59 UTC, chrismatix commented on backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java
> +    //TODO: Add return value and correct exception handleling
Same comment about implementing TODO or removing comment if no longer required

2022-10-17 11:59 UTC, chrismatix commented on backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java
> +            //TODO: do better error handleling
question: Better how? 🤔

2022-10-17 11:59 UTC, chrismatix commented on backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/ComponentDetails.java
> +    @JsonAnySetter
TIL! Very cool feature

2022-10-17 11:59 UTC, chrismatix commented on repositories.bzl
> +    "commons-io:commons-io:2.11.0",
Where is the commons package being used?

2022-10-17 12:30 UTC, chrismatix approved these changes

2022-10-17 12:51 UTC, merged