[#722] Add AKHQ as optional tool
airyhq/airy pull request #847
Opened 2021-02-02 18:46 UTC by ljupcovangelski

AKHQ is deployed if `tools.akhq.enabled=true` in the `airy.yaml` file.
Basic authentication is enabled. Default username is `admin`. The password can be retrieved from a configMap:
```
kubectl get configmap akhq-config -o jsonpath="{.data.password}"
```

2021-02-02 18:59 UTC, ljupcovangelski commented on infrastructure/helm-chart/values.yaml
> +    toolsHost: "tools.airy"
Akhq will be deployed and accessible through akhq.{toolsHost} or `akhq.tools.airy`.
I didn't add the DNS entry for the Vagrantbox, as `/etc/hosts` doesn't accept wildcard certificates.

Open to suggestions for this, maybe one option would be to do `tools.airy/akhq`, but this doesn't work out of the box and some tweak would be needed for traefik to strip the `/akhq` prefix, before the request is sent to the app.

2021-02-03 08:38 UTC, pascal-airy approved these changes
glad you made the auth work :)

2021-02-03 09:55 UTC, lucapette commented on infrastructure/airy.tpl.yaml
> +    enabled: true
I wouldn't have this enabled by default

2021-02-03 09:58 UTC, lucapette requested changes
I like it! but it's strange that it's an optional component and it's enabled by default.

We should also provide some docs about it somewhere but I suppose that can be done in the #846 

We do need a followup ticket to make this available in the vagrant instance though

2021-02-08 15:45 UTC, lucapette approved these changes
:shipit:

2021-02-09 07:22 UTC, merged