[#665] Build UI aspect of channels page
airyhq/airy pull request #986
Opened 2021-02-15 16:39 UTC by ogbeche77

Fixes #665

2021-02-22 11:16 UTC, AitorAlgorta requested changes

2021-02-22 11:16 UTC, AitorAlgorta commented on frontend/ui/src/pages/Channels/ChannelsSources/ChannelsConnected.tsx
> +                  const channelName = channel.metadata.name;
maybe just use `channel.metadata.name`?

2021-02-22 11:16 UTC, AitorAlgorta commented on frontend/ui/src/pages/Channels/ChannelsSources/ChannelsConnected.tsx
> +                  <button className={styles.extraChannel} title="Click for more details">
why create a new button? we already have this one in our library https://components.airy.co/?path=/story/airy-components-cta-linkbutton--link-button-component

2021-02-22 11:16 UTC, AitorAlgorta commented on frontend/ui/src/pages/Channels/ChannelsSources/ChatPluginSource.tsx
> +        showConnectedChannels={chatPluginSources.length > 0}
I think you could reduce the number of props a lot if you just make some small changes

2021-02-23 08:30 UTC, AitorAlgorta approved these changes
LGTM 🚀

2021-02-23 08:30 UTC, bitboxer approved these changes
👍 🥳 Awesome.

2021-02-23 08:52 UTC, merged